[package]
name = "custom-labels"
version = "0.4.0"
edition = "2021"
license = "Apache-2.0"
keywords = ["profiling", "pprof", "polarsignals", "parca"]
description = "Custom labels for profilers"
homepage = "https://polarsignals.com"
repository = "https://github.com/polarsignals/custom-labels"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = { version = "0.70", default-features = false, features = ["runtime"] }
cc = "1.0"

[dev-dependencies]
rand = "0.8.5"
axum = "0.8"
tokio = { version = "1.44", features = ["full"] }
anyhow = "1.0"
markdown = "1.0.0-alpha.23"

[dependencies]
libc = "0.2"
pin-project = "1.1.10"
